#!/bin/sh
# Remap Caps Lock: hold = Ctrl, tap = Escape
#
# Safe to call multiple times — xcape is restarted, xmodmap is idempotent.
#
# HOW IT WORKS
# ------------
# Caps Lock (keycode 66) is assigned the keysym Hyper_L, which is unique to
# this key once moved out of mod4.  Hyper_L is then added to the Control
# modifier group, so holding Caps Lock acts as Ctrl.  xcape watches for a
# solo Hyper_L tap (< 200 ms) and sends Escape — it never matches the
# physical Ctrl keys (Control_L / Control_R), so those are unaffected.
#
# LIMITATIONS
# -----------
# - X11 only.  On Wayland this script does nothing; use xremap or keyd instead.
# - GNOME: gnome-settings-daemon resets xkb after login.  This script must
#   be called a second time via ~/.config/autostart/caps-remap.desktop, which
#   runs after gnome-settings-daemon has finished.  install-x11.sh sets that up.
# - startx/xinit users: ~/.xprofile is NOT sourced.  Add a call to this script
#   in ~/.xinitrc instead.
# - keycode 66 is the Caps Lock keycode on the vast majority of keyboards, but
#   is not guaranteed on all hardware.  Verify with: xev | grep keycode

# Remove the caps-lock toggle (lock modifier group).
xmodmap -e "clear Lock"

# Point Caps Lock at Hyper_L — a keysym not generated by any physical key once
# we move it out of mod4 below.
xmodmap -e "keycode 66 = Hyper_L"

# Hyper_L starts life in mod4 (Super/Hyper group).  Remove it so it can live
# solely in Control.  The || true guards against the case where it is already
# absent (e.g. a second invocation).
# NOTE: this also evicts keycode 207 (a second Hyper_L entry present on some
# systems) from mod4 — benign on keyboards without a physical Hyper key.
xmodmap -e "remove mod4 = Hyper_L" 2>/dev/null || true

# Add Hyper_L to the Control group so Caps Lock acts as Ctrl when held.
xmodmap -e "add Control = Hyper_L" || true

# (Re)start xcape.  -t 200: taps shorter than 200 ms produce Escape; anything
# longer is treated as a Ctrl hold.  Raise to 300–500 if taps feel missed.
if command -v xcape >/dev/null 2>&1; then
    pkill -x xcape 2>/dev/null || true
    xcape -t 200 -e 'Hyper_L=Escape'
else
    echo "caps-remap: xcape not found — tap-to-Escape will not work" >&2
fi
