set backspace=indent,eol,start
set autoindent
syntax on
set hlsearch
set ignorecase
set smartcase
set linebreak
set incsearch
set showcmd
set hidden
set noswapfile
colorscheme blue
set expandtab
set shiftwidth=4
set tabstop=4
set smarttab
set showbreak=>
set breakindent
set ruler
set wildmenu
